import type { Metadata } from "next";
import { Inter } from "next/font/google";

import Navbar from "@/components/navbar/Navbar";

import  Sidebar  from "@/components/sidebar";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    
        
        <div className="relative z-10">
          <Navbar  />
          <div className="hidden md:flex mt-16 max-w-48 flex-col fixed inset-y-0 ">
              <Sidebar/>
          </div>
          {children}
        </div>

  );
}
